### ISSUE TITLE
Spurious test failure of large_high_align on x64 MSVC

### ISSUE THREAD

**Issue by jonas-schievink** [jonas-schievink/aligned_alloc.rs#4]
The test allocates 1 MiB aligned to 1 MiB, so it shouldn't really hit OOM (I think). Yet [this log](https://ci.appveyor.com/project/jonas-schievink/aligned-alloc-rs/build/1.0.44/job/e5i4tow0tjcl59ym) indicates that the allocation failed (by returning a NULL pointer).

All other builds have passed, so this might even be specific to `x86_64-pc-windows-msvc`.

**Comment by jonas-schievink** [comment]
I've reproduced this for both `small_high_align` and `large_high_align` under wine:

```
running 6 tests
test tests::align_less_than_sizeof_usize ... ok
test tests::align_not_power_of_two ... ok
test tests::align_zero ... ok
test tests::large_high_align ... ok
test tests::small_high_align ... FAILED
test tests::small_low_align ... ok

failures:

---- tests::small_high_align stdout ----
	thread 'tests::small_high_align' panicked at 'assertion failed: !ptr.is_null()', src/lib.rs:148
```

```
running 6 tests
test tests::align_less_than_sizeof_usize ... ok
test tests::align_not_power_of_two ... ok
test tests::align_zero ... ok
test tests::large_high_align ... FAILED
test tests::small_high_align ... ok
test tests::small_low_align ... ok

failures:

---- tests::large_high_align stdout ----
	thread 'tests::large_high_align' panicked at 'assertion failed: !ptr.is_null()', src/lib.rs:157
```
